{
 "title": "Remo",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Humidity",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    { "expr": "remo_humidity" }
   ]
  },
  {
   "title": "Temperature",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "format": "celsius",
   "valueName": "avg",
   "targets": [
    { "expr": "remo_temperature" }
   ]
  },
  {
   "title": "Illumination",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "remo_illumination" }
   ]
  },
  {
   "title": "Instantaneous Electric Energy",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "remo_measured_instantaneous_energy_watt"
    }
   ]
  },
  {
   "title": "Cumulative Electric Energy",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "kwatt" }
   ],
   "targets": [
    {
     "expr": "remo_cumulative_electric_energy_kilowatt"
    }
   ]
  }
 ]
}